spring:
  application:
    name: spring_cloud_zipkin
  main:
    allow-bean-definition-overriding: true
server:
  port: 9411
management:
  metrics:
    web:
      server:
        auto-time-requests: false